name: Code Quality

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '18'

jobs:
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint with report
        run: |
          npm run lint -- --format=json --output-file=eslint-report.json
          npm run lint
        continue-on-error: true

      - name: Run Prettier check
        run: npm run format:check

      - name: Run TypeScript check
        run: npm run type-check

      - name: Check bundle size
        run: |
          npm run build
          npx bundlesize
        continue-on-error: true

      - name: Upload ESLint report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: eslint-report
          path: eslint-report.json
          retention-days: 7

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run dependency security audit
        run: |
          echo "🔍 Running dependency security audit..."
          
          # Run npm audit and capture exit code
          if npm audit --audit-level=moderate; then
            echo "✅ No moderate or higher vulnerabilities found"
          else
            echo "⚠️ Found vulnerabilities, checking severity..."
            
            # Run detailed audit for high/critical only
            if npm audit --audit-level=high; then
              echo "ℹ️ Only low/moderate vulnerabilities found - continuing"
            else
              echo "❌ High or critical vulnerabilities found!"
              echo "Please run 'npm audit fix' to resolve security issues"
              exit 1
            fi
          fi

  license-check:
    name: License Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check licenses
        run: |
          npx license-checker --onlyAllow 'MIT;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC;0BSD' --summary
        continue-on-error: true
